"""create_production_tables

Revision ID: c6d0b20b9243
Revises: 79ee19cf14fd
Create Date: 2026-09-29 01:46:23.890111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d0b20b9243'
down_revision: Union[str, Sequence[str], None] = '79ee19cf14fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='campaignstatus'), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('current_daily_limit', sa.Integer(), nullable=False),
    sa.Column('warmup_day', sa.Integer(), nullable=False),
    sa.Column('total_leads', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_replies', sa.Integer(), nullable=False),
    sa.Column('total_bounces', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_offering', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index('ix_companies_org_domain', 'companies', ['organization_id', 'domain'], unique=False)
    op.create_index(op.f('ix_companies_organization_id'), 'companies', ['organization_id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('has_mx', sa.Boolean(), nullable=False),
    sa.Column('has_spf', sa.Boolean(), nullable=False),
    sa.Column('has_dkim', sa.Boolean(), nullable=False),
    sa.Column('has_dmarc', sa.Boolean(), nullable=False),
    sa.Column('spf_record', sa.Text(), nullable=True),
    sa.Column('dmarc_record', sa.Text(), nullable=True),
    sa.Column('mx_records_json', sa.JSON(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'domain_name', name='uq_org_domain')
    )
    op.create_index(op.f('ix_domains_organization_id'), 'domains', ['organization_id'], unique=False)
    op.create_table('email_provider_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.Enum('GMAIL', 'SMTP', 'MOCK', name='providertype'), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('sends_today', sa.Integer(), nullable=False),
    sa.Column('sends_this_hour', sa.Integer(), nullable=False),
    sa.Column('last_send_at', sa.DateTime(), nullable=True),
    sa.Column('last_reset_date', sa.String(length=10), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'account_email', name='uq_org_account_email')
    )
    op.create_index(op.f('ix_email_provider_accounts_organization_id'), 'email_provider_accounts', ['organization_id'], unique=False)
    op.create_index('ix_provider_accounts_org_active', 'email_provider_accounts', ['organization_id', 'is_active', 'is_healthy'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('subject_pattern', sa.String(length=500), nullable=False),
    sa.Column('body_pattern', sa.Text(), nullable=False),
    sa.Column('email_type', sa.Enum('INITIAL', 'FOLLOWUP_1', 'FOLLOWUP_2', name='emailtype'), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_organization_id'), 'email_templates', ['organization_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('suppression_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Enum('UNSUBSCRIBE', 'BOUNCE', 'COMPLAINT', 'MANUAL', name='suppressionreason'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_org_suppressed_email')
    )
    op.create_index(op.f('ix_suppression_entries_email'), 'suppression_entries', ['email'], unique=False)
    op.create_index(op.f('ix_suppression_entries_organization_id'), 'suppression_entries', ['organization_id'], unique=False)
    op.create_index('ix_suppression_org_email', 'suppression_entries', ['organization_id', 'email'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('key_offering', sa.Text(), nullable=True),
    sa.Column('enriched', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ENRICHING', 'ENRICHED', 'EMAIL_GENERATED', 'QUEUED', 'EMAILED', 'FOLLOWUP_1_SENT', 'FOLLOWUP_2_SENT', 'REPLIED', 'BOUNCED', 'UNSUBSCRIBED', name='leadstatus'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_org_lead_email')
    )
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index('ix_leads_org_campaign', 'leads', ['organization_id', 'campaign_id'], unique=False)
    op.create_index('ix_leads_org_status', 'leads', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('email_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('email_type', sa.Enum('INITIAL', 'FOLLOWUP_1', 'FOLLOWUP_2', name='emailtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SENT', 'FAILED', 'BOUNCED', name='emailstatus'), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('provider_account', sa.String(length=255), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('provider_thread_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_records_campaign_id'), 'email_records', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_email_records_idempotency_key'), 'email_records', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_email_records_lead_id'), 'email_records', ['lead_id'], unique=False)
    op.create_index('ix_email_records_lead_type', 'email_records', ['lead_id', 'email_type'], unique=False)
    op.create_index('ix_email_records_org_status', 'email_records', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_email_records_organization_id'), 'email_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_email_records_provider_message_id'), 'email_records', ['provider_message_id'], unique=True)
    op.create_index(op.f('ix_email_records_provider_thread_id'), 'email_records', ['provider_thread_id'], unique=False)
    op.create_index(op.f('ix_email_records_status'), 'email_records', ['status'], unique=False)
    op.create_table('enrichment_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'RETRY_WAIT', 'SENT', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('lease_worker_id', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_jobs_lead_id'), 'enrichment_jobs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_enrichment_jobs_organization_id'), 'enrichment_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_enrichment_jobs_status'), 'enrichment_jobs', ['status'], unique=False)
    op.create_table('enrichment_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('resolved_ip', sa.String(length=45), nullable=True),
    sa.Column('fetch_method', sa.String(length=50), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('headings_json', sa.JSON(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('summary_description', sa.Text(), nullable=True),
    sa.Column('key_offering', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_results_lead_id'), 'enrichment_results', ['lead_id'], unique=False)
    op.create_index(op.f('ix_enrichment_results_organization_id'), 'enrichment_results', ['organization_id'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('email_record_id', sa.Integer(), nullable=True),
    sa.Column('reply_body', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('INTERESTED', 'NOT_INTERESTED', 'OUT_OF_OFFICE', 'UNSUBSCRIBE', 'SPAM', 'UNKNOWN', name='replyclassification'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('provider_thread_id', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_record_id'], ['email_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replies_lead_id'), 'replies', ['lead_id'], unique=False)
    op.create_index(op.f('ix_replies_organization_id'), 'replies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_replies_provider_message_id'), 'replies', ['provider_message_id'], unique=True)
    op.create_index(op.f('ix_replies_provider_thread_id'), 'replies', ['provider_thread_id'], unique=False)
    op.create_table('send_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('email_record_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'RETRY_WAIT', 'SENT', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('lease_worker_id', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_record_id'], ['email_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_send_jobs_campaign_id'), 'send_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_send_jobs_email_record_id'), 'send_jobs', ['email_record_id'], unique=False)
    op.create_index(op.f('ix_send_jobs_idempotency_key'), 'send_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_send_jobs_lead_id'), 'send_jobs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_send_jobs_lease_expires_at'), 'send_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_send_jobs_lease_worker_id'), 'send_jobs', ['lease_worker_id'], unique=False)
    op.create_index(op.f('ix_send_jobs_organization_id'), 'send_jobs', ['organization_id'], unique=False)
    op.create_index('ix_send_jobs_poll', 'send_jobs', ['status', 'scheduled_for', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_send_jobs_scheduled_for'), 'send_jobs', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_send_jobs_status'), 'send_jobs', ['status'], unique=False)
    op.create_table('send_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('send_job_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('provider_response_code', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['send_job_id'], ['send_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_send_attempts_send_job_id'), 'send_attempts', ['send_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_send_attempts_send_job_id'), table_name='send_attempts')
    op.drop_table('send_attempts')
    op.drop_index(op.f('ix_send_jobs_status'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_scheduled_for'), table_name='send_jobs')
    op.drop_index('ix_send_jobs_poll', table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_organization_id'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_lease_worker_id'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_lease_expires_at'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_lead_id'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_idempotency_key'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_email_record_id'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_campaign_id'), table_name='send_jobs')
    op.drop_table('send_jobs')
    op.drop_index(op.f('ix_replies_provider_thread_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_provider_message_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_organization_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_lead_id'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_enrichment_results_organization_id'), table_name='enrichment_results')
    op.drop_index(op.f('ix_enrichment_results_lead_id'), table_name='enrichment_results')
    op.drop_table('enrichment_results')
    op.drop_index(op.f('ix_enrichment_jobs_status'), table_name='enrichment_jobs')
    op.drop_index(op.f('ix_enrichment_jobs_organization_id'), table_name='enrichment_jobs')
    op.drop_index(op.f('ix_enrichment_jobs_lead_id'), table_name='enrichment_jobs')
    op.drop_table('enrichment_jobs')
    op.drop_index(op.f('ix_email_records_status'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_provider_thread_id'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_provider_message_id'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_organization_id'), table_name='email_records')
    op.drop_index('ix_email_records_org_status', table_name='email_records')
    op.drop_index('ix_email_records_lead_type', table_name='email_records')
    op.drop_index(op.f('ix_email_records_lead_id'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_idempotency_key'), table_name='email_records')
    op.drop_index(op.f('ix_email_records_campaign_id'), table_name='email_records')
    op.drop_table('email_records')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_index('ix_leads_org_status', table_name='leads')
    op.drop_index('ix_leads_org_campaign', table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_suppression_org_email', table_name='suppression_entries')
    op.drop_index(op.f('ix_suppression_entries_organization_id'), table_name='suppression_entries')
    op.drop_index(op.f('ix_suppression_entries_email'), table_name='suppression_entries')
    op.drop_table('suppression_entries')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_email_templates_organization_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index('ix_provider_accounts_org_active', table_name='email_provider_accounts')
    op.drop_index(op.f('ix_email_provider_accounts_organization_id'), table_name='email_provider_accounts')
    op.drop_table('email_provider_accounts')
    op.drop_index(op.f('ix_domains_organization_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_companies_organization_id'), table_name='companies')
    op.drop_index('ix_companies_org_domain', table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
